version: '3.2'

services:

  base-python:
    image: cvs/base-python
    build: python
    container_name: cvs-base-python

  base-nginx:
    image: cvs/base-nginx
    build: nginx
    container_name: cvs-base-nginx

  base-janus:
    image: cvs/base-janus
    build: janus
    container_name: cvs-base-janus