version: '3.2'

networks:
  cvs:
    external: true

services:

  frontend-builder:
    build:
      context: ../../Web
      dockerfile: ../Docker/videoroom/builder.Dockerfile
    image: videoroom/frontend-builder
    container_name: videoroom-frontend-builder

  backend:
    image: cvs/videoroom-backend
    build:
      context: ../../Backend
      dockerfile: ../Docker/videoroom/backend.Dockerfile
    container_name: videoroom-backend
    command: python -m videoroom
    ports:
      - 8000:8000
    networks:
      - cvs

  frontend:
    build:
      context: ./
      dockerfile: ./frontend.Dockerfile
    image: cvs/videoroom-frontend
    container_name: videoroom-frontend
    command: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - cvs